version: "3"
services:
  apts:
    container_name: apts
    image: apts
    # The following options are useful when running 'protocoltest' below:
    #    -v: prints the name of each test as it is run; otherwise, printed more concisely
    #    -x: stop after the first test failure; otherwise, runs all tests
    #    --capture=tee-sys: print stdout/stderr to screen for all tests; otherwise, only prints for failed tests
    command: protocoltest -vx
    build:
      context: apts
    volumes:
      - ./apts/src/aut.py:/aries-protocol-test-suite/aut.py
    networks:
      - aries-playground-nw
networks:
  aries-playground-nw:
    external: true
