version: '3'
services:
  nginx:
    image: nginx
    command: /bin/bash -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/acapy.template > /etc/nginx/conf.d/acapy.conf && exec nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - aries-playground-nw

  test-center.localhost:
    image: igrantio/aries-cloudagent:0.5.6_v10_dx_fix
    command: /bin/bash -c "./startup.sh"
    container_name: test-center.localhost
    ports:
      - 8051:8001
    environment:
      AGENT_NAME: Test-Center
      ACAPY_ENDPOINT: http://test-center.localhost
      GENESIS_URL: https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis
      WEBHOOK_URL: http://test-center.webhook:8080
    volumes:
      - ./cloud-agent/startup.sh:/home/indy/startup.sh
    networks:
      - aries-playground-nw

  test-center.webhook:
    image: igrantio/aries-webhook-interceptor:0.1
    container_name: test-center.webhook
    ports:
      - 8081:8080
    networks:
      - aries-playground-nw

  data4Life-user.localhost:
    image: igrantio/aries-cloudagent:0.5.6_v10_dx_fix
    command: /bin/bash -c "./startup.sh"
    container_name: data4Life-user.localhost
    ports:
      - 8052:8001
    environment:
      AGENT_NAME: Data4Life-User
      ACAPY_ENDPOINT: http://data4Life-user.localhost
      GENESIS_URL: https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis
      WEBHOOK_URL: http://data4Life-user.webhook:8080
    volumes:
      - ./cloud-agent/startup.sh:/home/indy/startup.sh
    networks:
      - aries-playground-nw

  data4Life-user.webhook:
    image: igrantio/aries-webhook-interceptor:0.1
    container_name: data4Life-user.webhook
    ports:
      - 8082:8080
    networks:
      - aries-playground-nw

  travel-company.localhost:
    image: igrantio/aries-cloudagent:0.5.6_v10_dx_fix
    command: /bin/bash -c "./startup.sh"
    container_name: travel-company.localhost
    ports:
      - 8053:8001
    environment:
      AGENT_NAME: Travel-Company
      ACAPY_ENDPOINT: http://travel-company.localhost
      GENESIS_URL: https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis
      WEBHOOK_URL: http://travel-company.webhook:8080
    volumes:
      - ./cloud-agent/startup.sh:/home/indy/startup.sh
    networks:
      - aries-playground-nw

  travel-company.webhook:
    image: igrantio/aries-webhook-interceptor:0.1
    container_name: travel-company.webhook
    ports:
      - 8083:8080
    networks:
      - aries-playground-nw

networks:
  aries-playground-nw:
    external: true
