aca-py start \
    -it http 0.0.0.0 80 \
    -ot http \
    -e $ACAPY_ENDPOINT \
    --label $AGENT_NAME \
    --admin 0.0.0.0 8001 \
    --admin-insecure-mode \
    --genesis-url $GENESIS_URL \
    --wallet-type indy \
    --wallet-name $AGENT_NAME \
    --webhook-url $WEBHOOK_URL \
    --wallet-key qwerty123